Partial age form
interglobalvision/materialvodka-com pull request #23
Opened 2018-05-09 01:45 UTC by neener

2018-05-09 22:00 UTC, mixcas submitted a review, later dismissed
Its important that we use semantic variables, classes, and other identifiers that we create ourselves, can understand, and are project appropriate. Its better to learn from code you find and rewriting it yourself, rather than simply copy-pasting. That way you understand it better, and write code that is specific to the project.

Code works fine but there's some clean up to do

2018-05-09 22:00 UTC, mixcas commented on partials/agechecker-form.php
> +<div id="form-wrapper--dob">
@neener what are these classes/ids?

2018-05-09 22:00 UTC, mixcas commented on src/js/main.js
> +      const year = $('.year').val();
For these elements we should use more descriptive classes like `.birthday-month`, `.birthday-day`, `.birthday-year`

2018-05-09 22:00 UTC, mixcas commented on src/js/main.js
> +//const MaterialShop = new Shop();
@neener This is a temporary fix for the error you were getting but you should be careful not to commit changes we don't actually need.

2018-05-09 22:04 UTC, mixcas commented on src/js/main.js
> +//const MaterialShop = new Shop();
tip: run `git diff` to review your changes before git add/commit.

2018-05-10 18:23 UTC, mikeyrayvon requested changes

2018-05-10 18:23 UTC, mikeyrayvon commented on partials/agechecker-form.php
> +    <input class="birthday-month" name="month" value="" type="number" min="1" max="12" placeholder="MM" id="dob_mm">
use `id`s instead of classes when the identifier refers to a single element

we dashes in HTML attributes, camelCase in javascript, and underscores in PHP

please replace the underscores in these `id`s with dashes

2018-05-10 18:29 UTC, mikeyrayvon approved these changes

2018-05-10 18:37 UTC, merged