Detail single product
interglobalvision/materialvodka-com pull request #68
Opened 2018-05-23 22:38 UTC by mikeyrayvon

- detail single-product
- add "other stuff" products at bottom
- improve cart js & markup. 
- add cart functionality & styling
- add support for multiple product variant selects

2018-05-24 17:56 UTC, mixcas commented on single-product.php
> +  'meta_key' => '_igv_shopify_product_handle',
whats this used for?

2018-05-24 18:05 UTC, mikeyrayvon commented on single-product.php
> +  'meta_key' => '_igv_shopify_product_handle',
thats wrong. just fixed it

2018-05-24 18:53 UTC, mixcas requested changes
The code seems to work as expected. I just have my doubts about the reason for some changes. I won't fight against them tho.

I feel commenting the code where requested is more important.

2018-05-24 18:53 UTC, mixcas commented on src/js/shop.js
> +        this.product = product;
Why this move of saving the product instead of passing it as a param to other functions? Same with saving `this.variantId` instead of passing it and getting the values from the form on `addToCart`. 

I don't see a reason why the object should hold the some sort of _state_ for the form when we can just pull the values from it when needed. Maybe I'm missing something?

2018-05-24 18:53 UTC, mixcas commented on src/js/shop.js
> +  getVariantId() {
I don't understand this function at all. Some comments would be awesome

2018-05-24 19:57 UTC, mikeyrayvon commented on src/js/shop.js
> +  getVariantId() {
yea sorry bout that. will do

2018-05-24 19:58 UTC, mikeyrayvon commented
i'll comment everything

2018-05-24 22:00 UTC, mikeyrayvon commented
tbh I don't really understand that loop either. I sorta used my feelings to write it if u know what i mean...I added comments.

also passing `product` as a parameter

2018-05-25 01:57 UTC, mixcas approved these changes

2018-05-25 02:05 UTC, merged